### ISSUE TITLE
[BUG] Login state not reflected on landingpage view

### ISSUE THREAD

**Issue by flowdnb** [edumeet/edumeet-client#202]
**Describe the bug**
The login button does not change to 'Logout' after successful login on landingpage view. Also, the management client doesn't login the user. Both does however work on the lobby view.

**To Reproduce**
1. Go to the very first edumeet-client page
2. Click on 'Login' and log in with IdP
3. See button still shows 'Login' and management client does not automatically log in the user.

**Expected behavior**
The login button should show a logout button and the management client should log in the user, as in the lobby.

**Comment by N7Remus** [comment]
Fix is available, will be merged soon.

**Comment by flowdnb** [comment]
@N7Remus `edumeet-client:4.0-20241122-test` issue still persists
